spring:
  application:
    name: customer-service
    
    
eureka:
  instance:
     leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      
      
# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port